#!/usr/bin/env python3
"""
sync_to_sharepoint.py — Upload catalog .md files from a local folder to SharePoint Document Library.

Reads pre-built catalog .md files generated by sync_to_local.py and uploads them to SharePoint.
Run sync_to_local.py first to generate and review the catalog files, then run this script to publish.

Workflow:
    1. python scripts/sync_to_local.py --repo <org>/<repo> --output ./skill-registry
    2. Review files in ./skill-registry
    3, Select candidate files in ./skill-registry and copy to publish folder
    3. python scripts/sync_to_sharepoint.py --input ./publish

Usage:
    python scripts/sync_to_sharepoint.py --input ./publish
    python scripts/sync_to_sharepoint.py --input ./publish --dry-run

Required environment variables:
    SHAREPOINT_SITE_URL       e.g. https://bmgf.sharepoint.com/sites/AISkillsRegistry
    SHAREPOINT_CLIENT_ID      Azure app registration client ID
    SHAREPOINT_CLIENT_SECRET  Azure app registration client secret
    SHAREPOINT_TENANT_ID      Azure tenant ID

Optional environment variables:
    SKILL_LIBRARY_NAME        SharePoint document library name (default: Skill Registry)
"""

import argparse
import os
import sys
from pathlib import Path

from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext


# ── Config ────────────────────────────────────────────────────────────────────

SHAREPOINT_SITE_URL = os.environ.get("SHAREPOINT_SITE_URL", "")
SHAREPOINT_CLIENT_ID = os.environ.get("SHAREPOINT_CLIENT_ID", "")
SHAREPOINT_CLIENT_SECRET = os.environ.get("SHAREPOINT_CLIENT_SECRET", "")
SHAREPOINT_TENANT_ID = os.environ.get("SHAREPOINT_TENANT_ID", "")
SKILL_LIBRARY_NAME = os.environ.get("SKILL_LIBRARY_NAME", "Skill Registry")

DEFAULT_INPUT_DIR = "./skill-registry"


# ── Helpers ───────────────────────────────────────────────────────────────────

def check_env():
    missing = []
    for var in ["SHAREPOINT_SITE_URL", "SHAREPOINT_CLIENT_ID", "SHAREPOINT_CLIENT_SECRET", "SHAREPOINT_TENANT_ID"]:
        if not os.environ.get(var):
            missing.append(var)
    if missing:
        print(f"Error: Missing required environment variables: {', '.join(missing)}")
        sys.exit(1)


def find_catalog_files(input_dir: Path) -> list[Path]:
    """Find all .md files in the local catalog folder."""
    return list(input_dir.glob("*.md"))


# ── SharePoint ─────────────────────────────────────────────────────────────────

def connect_to_sharepoint() -> ClientContext:
    credentials = ClientCredential(SHAREPOINT_CLIENT_ID, SHAREPOINT_CLIENT_SECRET)
    ctx = ClientContext(SHAREPOINT_SITE_URL).with_credentials(credentials)
    ctx.load(ctx.web)
    ctx.execute_query()
    print(f"Connected to SharePoint: {ctx.web.url}")
    return ctx


def get_existing_files(ctx: ClientContext) -> set[str]:
    """Returns filenames already in the SharePoint document library."""
    library = ctx.web.lists.get_by_title(SKILL_LIBRARY_NAME)
    items = library.items.select(["FileLeafRef"]).get().execute_query()
    return {item.properties.get("FileLeafRef", "") for item in items}


def upload_document(ctx: ClientContext, filename: str, content: str, existing_files: set[str], dry_run: bool):
    """Upload or overwrite a catalog document in the SharePoint document library."""
    action = "Updated" if filename in existing_files else "Uploaded"
    if dry_run:
        print(f"  [dry-run] Would {action.lower()}: {filename}")
        return
    folder = ctx.web.get_folder_by_server_relative_url(
        f"{ctx.web.server_relative_url}/{SKILL_LIBRARY_NAME}"
    )
    folder.upload_file(filename, content.encode("utf-8")).execute_query()
    print(f"  {action}: {filename}")


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Upload pre-built catalog .md files to SharePoint Document Library."
    )
    parser.add_argument(
        "--input", "-i",
        default=DEFAULT_INPUT_DIR,
        help=f"Local folder containing catalog .md files (default: {DEFAULT_INPUT_DIR})"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be uploaded without actually uploading"
    )
    args = parser.parse_args()

    input_dir = Path(args.input)
    if not input_dir.exists():
        print(f"Error: Input folder not found: {input_dir}")
        print(f"Run sync_to_local.py first to generate catalog files.")
        sys.exit(1)

    # Find catalog files
    catalog_files = find_catalog_files(input_dir)
    if not catalog_files:
        print(f"No .md files found in {input_dir}. Nothing to upload.")
        sys.exit(0)
    print(f"Found {len(catalog_files)} catalog file(s) in {input_dir}")

    if args.dry_run:
        print("\n[dry-run mode] No files will be uploaded.\n")

    if not args.dry_run:
        check_env()
        print("\nConnecting to SharePoint...")
        ctx = connect_to_sharepoint()
        print(f"\nFetching existing files from '{SKILL_LIBRARY_NAME}' library...")
        existing_files = get_existing_files(ctx)
        print(f"Found {len(existing_files)} existing file(s) in SharePoint.")
    else:
        ctx = None
        existing_files = set()

    print("\nUploading catalog files...")
    uploaded = 0
    for catalog_path in catalog_files:
        print(f"\nProcessing: {catalog_path.name}")
        content = catalog_path.read_text(encoding="utf-8")
        upload_document(ctx, catalog_path.name, content, existing_files, args.dry_run)
        uploaded += 1

    print(f"\nDone. {'Would upload' if args.dry_run else 'Uploaded'}: {uploaded} file(s)")


if __name__ == "__main__":
    main()